// Prisma Migrations - Initial Schema

// Initial migration: create all tables with proper indexes and constraints
// Migration file: migrations/001_initial_schema.sql

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Enable full text search
CREATE EXTENSION IF NOT EXISTS "unaccent";

-- Create initial schema will be auto-generated by Prisma migrate command
